import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="relative min-h-screen bg-[url('/fondo.jpg')] bg-repeat bg-center bg-[length:300px_260px] flex flex-col items-center justify-center p-4 sm:p-8 overflow-hidden">

          <div className="relative z-10 w-full flex flex-col items-center">
            {children}
            <footer className="mt-10 text-center text-[var(--paper)] text-sm opacity-80">
              Antigua Devs &copy; {new Date().getFullYear()}
            </footer>
          </div>
        </div>
      </body>
    </html>
  );
}
